[environments]
  [environments.development]
  db = "snooty_dev"

  [environments.staging]
  db = "snooty_stage"

  [environments.production]
  db = "snooty_prod"

  [environments.dotcomstg]
  db = "snooty_dotcomstg"

  [environments.dotcomprd]
  db = "snooty_dotcomprd"
