[[genres]]
name = "reference"

[[genres]]
name = "tutorial"

# trying to map to docs "name" property 
# for target_products and sub_products
# as much as possible
[[target_products]]
name = "atlas"

  [[target_products.sub_products]]
  name = "atlas-app-services"
  display_name = "App Services"

  [[target_products.sub_products]]
  name = "charts"
  display_name = "Charts"

  [[target_products.sub_products]]
  name = "atlas-cli"
  display_name = "Atlas CLI"

  [[target_products.sub_products]]
  name = "data-api"
  display_name = "Data API"

  [[target_products.sub_products]]
  name = "data-federation"

  [[target_products.sub_products]]
  name = "data-lake"

  [[target_products.sub_products]]
  name = "device-sync" #404

  [[target_products.sub_products]]
  name = "kubernetes-operator"

  [[target_products.sub_products]]
  name = "online-archive"

  [[target_products.sub_products]]
  name = "search"

  [[target_products.sub_products]]
  name = "stream-processing"

  [[target_products.sub_products]]
  name = "triggers"

[[target_products]]
name = "bi-connector"
display_name = "BI Connector"

[[target_products]]
name = "com"
display_name = "Cloud Manager"

[[target_products]]
name = "c2c"
display_name = "Cluster-to-Cluster Sync"

[[target_products]]
name = "community-kubernetes-operator"  # 404

[[target_products]]
name = "compass"

[[target_products]]
name = "database-tools"

[[target_products]]
name = "drivers"

[[target_products]]
name = "enterprise-kubernetes-operator"

[[target_products]]
name = "kafka-connector"

[[target_products]]
name = "mongodb-analyzer" # 404
display_name = "MongoDB Analyzer"

[[target_products]]
name = "mongocli"
display_name = "MongoDB CLI"

[[target_products]]
name = "visual-studio-extension"
display_name = "MongoDB for VS Code"

[[target_products]]
name = "mongodb-shell"
display_name = "MongoDB Shell"

[[target_products]]
name = "onprem" # verify
display_name = "Ops Manager"

[[target_products]]
name = "realm"

  [[target_products.sub_products]]
  name = "cpp"
  display_name = "C++ SDK"

  # nestled under docs-realm 
  [[target_products.sub_products]]
  name = "flutter"
  display_name = "Dart Flutter SDK"

  [[target_products.sub_products]]
  name = "java"
  display_name = "Java SDK"

  [[target_products.sub_products]]
  name = "kotlin"
  display_name = "Kotlin SDK"

  [[target_products.sub_products]]
  name = "dotnet"
  display_name = ".NET SDK"

  [[target_products.sub_products]]
  name = "react-native"
  display_name = "React Native SDK"

  [[target_products.sub_products]]
  name = "swift"
  display_name = "Swift SDK"

  [[target_products.sub_products]]
  name = "node"
  display_name = "Node.js SDK"

  [[target_products.sub_products]]
  name = "web"
  display_name = "Web SDK"

[[target_products]]
name = "docs-relational-migrator"
display_name = "Relational Migrator"

[[target_products]]
name = "docs"  # verify
display_name = "Server"

[[target_products]]
name = "spark-connector"  # verify

# validated against existing search documents
[[programming_languages]]
name = "objective-c"
display_name = "Objective C"

[[programming_languages]]
name = "c"

[[programming_languages]]
name = "csharp"
display_name = "C#"

[[programming_languages]]
name = "cpp"
display_name = "C++"

[[programming_languages]]
name = "dart"

[[programming_languages]]
name = "go"

[[programming_languages]]
name = "java"

[[programming_languages]]
name = "kotlin"

[[programming_languages]]
name = "php"
display_name = "PHP"

[[programming_languages]]
name = "python"

[[programming_languages]]
name = "ruby"

[[programming_languages]]
name = "rust"

[[programming_languages]]
name = "scala"

[[programming_languages]]
name = "swift"

[[programming_languages]]
name = "javascript/typescript"  # validate
display_name = "JavaScript/TypeScript"

[[programming_languages]]
name = "shell"

[[programming_languages]]
name = "json"
display_name = "JSON"

[[programming_languages]]
name = "realmql"
display_name = "RealmQL"

[[programming_languages]]
name = "graphql"
display_name = "GraphQL"

[[programming_languages]]
name = "mql"
display_name = "MQL"
