name = "test_data"

[constants]
name = "MongoDB name"
title = "MongoDB title"

[substitutions]
guides = "MongoDB Guides"

[deprecated_versions]
manual = ["v2.2", "v2.4", "v2.6", "v3.0", "v3.2", "v3.4"]
mms = ["v1.1", "v1.2", "v1.3"]