[[target_platforms]]
name = "atlas"

[[target_platforms.versions]]
name = "v1.2"

[[target_platforms.sub_platforms]]
name = "c_driver"

[[test_facet]]
name = "test"

[[test_facet.tested_nest]]
name = "test_nest"