from typing import Any, Dict, List, Optional, Tuple, Union
from . import cursor


class Collection:
    def find(self,
             filter: Dict[str, Any],
             projection: Optional[Dict[str, Any]]=None,
             cursor_type: Optional[cursor.CursorType]=None) -> Any: ...
    def delete_one(self, filter: Dict[str, Any]) -> Any: ...
    def insert_one(self, doc: Dict[str, Any]) -> Any: ...
    def replace_one(self, filter: Dict[str, Any], doc: Dict[str, Any], upsert: bool=False) -> Any: ...
    def update_one(self, filter: Dict[str, Any], doc: Dict[str, Any], upsert: bool=False) -> Any: ...
    def create_index(self, keys: Union[str, List[Tuple[str, int]]], name: Optional[str], unique: Optional[bool]) -> Any: ...
    def index_information(self) -> Any: ...
