[[facets]]
category="target_platforms"
value = "atlas"

  [[facets.sub_facets]]
  category="versions"
  value = "v1.2"

  [[facets.sub_facets]]
  category="sub_platforms"
  value = "c_driver"

[[facets]]
category="test_facet"
value = "test"

  [[facets.sub_facets]]
  category="tested_nest"
  name = "test_nest"