[[facets]]
category="target_platforms"
value = "atlas"
  [[facets.sub_facets]]
  category="sub_platforms"
  value = "atlas-app-services"

[[facets]]
category="test_facet"
value = "test"

  [[facets.sub_facets]]
  category="tested_nest"
  value = "test_nest"