from ..events import FileSystemEventHandler
from .api import ObservedWatch


class Observer:
    def schedule(self, handler: FileSystemEventHandler, path: str, recursive: bool=True) -> ObservedWatch: ...
    def unschedule(self, watcher: ObservedWatch) -> None: ...
    def start(self) -> None: ...
    def join(self) -> None: ...
    def stop(self) -> None: ...
